[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clippy]
install_crate = "rustfmt"
command = "cargo"
args = ["clippy"]

[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.wasm]
command = "cargo"
args = ["check", "--target", "wasm32-unknown-unknown"]

[tasks.create_docs]
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.docs]
command = "open"
args = ["./target/doc/wincounter/index.html"]

dependencies = ["create_docs"]

[tasks.fuck]
command = "grep"
args = ["-RInE", "'fuck|shit|fart|nimrod|schmuck|asshole|stupid'", "src"]

[tasks.ayce]
dependencies = [
    "fmt",
    "build",
    "test",
    "clippy",
    "wasm",
    "create_docs"
]

# ayce = All You Can Eat
[tasks.default]
alias = "ayce"